### ISSUE TITLE
Mount is lost when driver is deleted/re-created

### ISSUE THREAD

**Issue by sjberman** [spiffe/spiffe-csi#16]
When the csi driver is deleted and re-created for whatever reason (upgrade, crash, etc.) the old socket mount is lost, and all existing workloads that were attached will lose that connection. Even when a new csi driver starts up, it only attaches when new workload creation events occur, and is unaware of existing workloads that have a broken mount.

Ideally the csi driver should be able to remount existing workloads if the mount is unhealthy or broken.

The workaround is to re-roll the workloads once the new csi driver is running, so that it can see the new creation events and attach the new mount.

**Comment by azdagron** [comment]
Thanks for reporting this @sjberman! It looks like CSI grew a way for the drivers to report health in 1.19 (with some improvements along the way). https://kubernetes.io/blog/2021/04/16/volume-health-monitoring-alpha-update/. Looks like the feature is still in alpha stage. From what I can tell, the kubelet is still only in an advisory position during alpha, and will only report health failures instead of taking any proactive steps. Still we should be able to update the driver to report health.

> Ideally the csi driver should be able to remount existing workloads if the mount is unhealthy or broken.

Unfortunately, I don't think the driver is in a position to do this proactively. It would require support from the kubelet. Maybe in the beta stage, the kubelet will learn to take automated actions (e.g. cycling the pod).

**Comment by azdagron** [comment]
I think this is solved by using a hostPath between the Workload API implementation (e.g. SPIRE agent) and CSI driver instead of emptyDir. The mount will survive the pod restart. I've updated examples, etc. in #17 to communicate this.
