### ISSUE TITLE
Relabeling fails when SELinux is enabled

### ISSUE THREAD

**Issue by bendikp** [spiffe/spiffe-csi#42]
Thanks for the great work on this CSI driver.

We are trying to get the CSI driver working on clusters with SELinux enabled (RKE2 `v1.24`  and OpenShift `v1.23`). 

When deploying the example-workload we get the following error:
```
CreateContainerError (failed to generate container "2d1bd76ada39d781110f6559ebe324f9f2c76f6a5fb0ce324426089ae4593f0b" 
spec: failed to generate spec: relabel "/var/lib/kubelet/pods/86e8ad89-bf07-421c-9ae2-a53745ce91e8/volumes/kubernetes.io~csi/spiffe-workload-api/mount" 
with "system_u:object_r:container_file_t:s0:c442,c843" failed: 
lsetxattr /var/lib/kubelet/pods/86e8ad89-bf07-421c-9ae2-a53745ce91e8/volumes/kubernetes.io~csi/spiffe-workload-api/mount: read-only file system)
```

It seems to be related to SELinux and that the node isn't able to run `lsetxattr` on the mount since it's mounted "read-only".

In the [kubernetes-csi docs](https://kubernetes-csi.github.io/docs/ephemeral-local-volumes.html#read-only-volumes) is states that it is possible to mount the volume "read-only" to the container and "read-write" to the node. Is this an option to solve this issue?

**Comment by azdagron** [comment]
Looking at the documentation you linked, I think it is safe for us to mount it read-write, but (counter-intuitively) only when the pod is mounting it read-only. We can't enforce the pod mount to be read-only since that could break existing deployments using this driver. We'll need to give such deployments (if any) time to adapt. This could be an opt-in behavior (via a config flag) that we eventually deprecate.

**Comment by bendikp** [comment]
This sounds promising 👍 I'm not that fluent in programming, but I'm happy to assist with testing if that's needed.

**Comment by erikgb** [comment]
@azdagron I am really glad to hear that this should be fixable. I'm thinking that this change (making `readOnly: true` mandatory) will break the UX of this driver at some point, even if we introduce the change as an opt-in. As a maintainer, I would prefer to break this as early as possible. And I think it is very unlikely that many are using this driver at it's early stage. So I'll vote for just changing this, as they did in https://github.com/cert-manager/csi-driver when fixing the same issue as this one.

**Comment by azdagron** [comment]
The version number can be misleading. I think you'd be [surprised](https://github.com/search?p=13&q=%22csi.spiffe.io%22&type=Code), particularly becomes this driver has been used somewhat recently in the istio docs that describe the SPIRE integration.

Furthermore, this is a pre-prod maturity level project so we've already committed to best-effort compatibility.

If our examples already had the CSI volume marked readOnly, then I'd be much more amenable to just making the change. Since they don't, and since I can't find any instances out in the wild where that is true, I'm hesitant to just break everyone who absentmindedly bumps the version from 0.1.0 to 0.2.0.

I need to ruminate on this a bit more.

**Comment by erikgb** [comment]
@azdagron I see. Would it be possible if the driver set the mounted volume as read/write only if the CSI volume is marked as readOnly by the user? Sounds a bit counter-intuitive, but I cannot see what would be wrong with doing that. And then we can introduce the validation (enforcing `readOnly: true`) behind a feature flag that will eventually be removed (enabled by default).

**Comment by erikgb** [comment]
> Yep. I think that is the safest thing we can do for now. I'll put up this change shortly for review.

@azdagron Thanks a lot! Feel free to add me for review.

**Comment by azdagron** [comment]
PR #44 has been opened to address this.
