### ISSUE TITLE
TImeline for GA ?

### ISSUE THREAD

**Issue by aelbarkani** [spiffe/spiffe-csi#7]
Hi ! Thanks for this awesome component ! Is there any timeline to make it GA/stable ?
This is definitely a must have for multi-tenant clusters in an enterprise context where the containers don't/shouldn't have privileged access.

**Comment by azdagron** [comment]
GA/stable means different things to different people, so it's kind of hard to tell exactly what you are asking but I'll try my best to answer.

In terms of code completeness, I think this component is pretty much done. It has a fairly simple job. One thing that is lacking is probably just early adoption from the community that puts it through it's paces so we can identity and work through any issues.

From a SPIFFE project maturity perspective, it is in the [Development](https://github.com/spiffe/spiffe/blob/main/MATURITY.md#development-). In order to move into the pre-production maturity phase, I think we're missing documentation, a security policy, and most importantly, unit and automated tests, of which we have none.

I put in the initial development work, but am currently spread thin tackling other things. I don't have a firm idea of when I'll get back to this. Community contributions would be more than welcome and I'd be happy to shepherd that work.

**Comment by aelbarkani** [comment]
Thanks @azdagron ! We'll start testing it and let you know about any issues we identify.
